Simplify pre-compiled regular expressions for sigils
stepchowfun/tagref pull request #218
Opened 2024-03-12 09:01 UTC by vedang

I discovered `tagref` today, when looking for a system inspired from GHC notes. I was delighted and tried it on a code-base where I have been writing notes, but it didn't work! I am not sure why, but let me describe the problem:

* Setup: Here is my sysinfo, as published by `neofetch`:
     OS: macOS 14.3.1 23D60 arm64
     Host: MacBookAir10,1
     Shell: fish 3.7.0
     Terminal: tmux
     CPU: Apple M1

On this system, `tagref` did not recognize any tags in my code, even when I had tags.
```
─> tagref
0 tags, 0 tag references, 0 file references, and 0 directory references validated in 464 files.
```

The problem seems to be in the capture group used in the regular expressions, which I verified using `rg` and `gsed`:
```
─> rg "\[\s*tag\s*:.*\s*\]"
components/whatsapp/src/ai/salher/whatsapp/core.clj
267:;; ## [tag:GIFs need to be converted to video/mp4 format]

components/chapters/src/ai/salher/chapters/core.clj
173:;;; ## [tag:Rules for deciding when we should update a chapter record]
185:;;; ## [tag:Rules to mark a chapter as DONE for now]
...

─> cat components/whatsapp/src/ai/salher/whatsapp/core.clj | gsed -En '/\[\s*tag\s*:\s*([^\]\s]*)\]/p'

─> cat components/whatsapp/src/ai/salher/whatsapp/core.clj | gsed -En '/\[\s*tag\s*:\s*.*\]/p'
;; ## [tag:GIFs need to be converted to video/mp4 format]

─> cat components/whatsapp/src/ai/salher/whatsapp/core.clj | gsed -En 's/.*\[\s*tag\s*:\s*(.*)\s*\].*/\1/p'
GIFs need to be converted to video/mp4 format
```

On seeing this, I tried to understand what the expressions are trying to do, and simplify them. My current understand is as follows:

1. Look for a starting square-bracket `[`
2. There can be 0 or more spaces between the square bracket and the sigil, ignore them.
3. Match the sigil
4. There can be 0 or more spaces between the sigil and `:` token, ignore them
5. There can be 0 or more spaces between the `:` token and the actual identifier, ignore them
6. Capture the identifier.
7. There can be 0 or more spaces between the end of the identifier and the closing square-bracket, ignore them.
8. Stop at the closing square-bracket `]`

With this in mind, I changed the capture group to a lazy-capture (from `([^\\]\\s]*)` to `(\\w.*?)`. This ensures that everything is captured until the closing square bracket (ignoring all empty space immediately before the closing bracket). The only constraint it imposes is that the first character of the identifier should be a letter, digit or underscore (via the `\w`). This is to ensure that `[tag:]` is not treated as a valid tag.

After this change, `tagref` is now working correctly on my local system. I ran `cargo tests` (all passing) and also tested on my own project, which now shows:
```
─> tagref
21 tags, 24 tag references, 0 file references, and 0 directory references validated in 464 files.
```

A clear description of the change.

**Status:** Ready / In development

**Fixes:** Link to issue (if applicable)

2024-03-12 21:52 UTC, stepchowfun commented
Hi @vedang, thank you so much for this pull request and for your thorough investigation!

If my understanding is correct, the problem you encountered is that Tagref currently doesn't allow spaces in tag names, so it wasn't detecting your tags which have spaces—is that correct?

I just want to confirm that this is not a bug, per se, but a request for a change in the behavior.

2024-03-12 21:54 UTC, stepchowfun commented
Unrelated: I'm not sure why the CI is failing on Windows, but it seems unrelated to this PR. Feel free to ignore it.

2024-03-13 02:37 UTC, vedang commented
> If my understanding is correct, the problem you encountered is that Tagref currently doesn't allow spaces in tag names, so it wasn't detecting your tags which have spaces—is that correct?

Yes, that's right. Sorry for not stating it clearly! All my tags use spaces and I think this is a useful change in behaviour.

2024-03-13 08:28 UTC, stepchowfun requested changes
Added a few comments, but otherwise looks good.

Would you mind also doing the following: bump the version in `[file:Cargo.toml]` to `1.10.0`, run `cargo build` to update `[file:Cargo.lock]`, and update `[file:CHANGELOG.md]` with a note like:

```md
## [1.10.0] - 2024-03-13

### Changed
- Tagref now supports whitespace in tag names and in paths in file and directory references.
```

2024-03-13 08:28 UTC, stepchowfun commented on src/main.rs
> +        "(?i)\\[\\s*{}\\s*:\\s*(\\w.*?)\\s*\\]",
I think this will break file references like `[file:.gitignore]`.

2024-03-13 08:28 UTC, stepchowfun commented on src/main.rs
> +        "(?i)\\[\\s*{}\\s*:\\s*(\\w.*?)\\s*\\]",
Similar concern here about directory references like `[dir:.github]`.

2024-03-13 08:28 UTC, stepchowfun commented on src/main.rs
> +        "(?i)\\[\\s*{}\\s*:\\s*(\\w.*?)\\s*\\]",
Proposal:

```rust
"(?i)\\[\\s*{}\\s*:\\s*([^\\]]*?)\\s*\\]",
```

2024-03-13 08:34 UTC, stepchowfun commented
Oh also would you mind changing the relevant part of `[file:README.md]` to something like:

```md
The name of a tag may consist of any UTF-8 text except the right square bracket `]`. Internal whitespace (as in `[tag:foo bar]`) is allowed, and surrounding whitespace (as in `[tag: baz ]`) is ignored. Tag names are case-sensitive, so `[tag:foo]` and `[tag:Foo]` are different tags.
```

2024-03-13 08:39 UTC, stepchowfun commented
Sorry one more thing; can you update the test in `[file:src/directive.rs]` that starts with:

```rust
    #[test]
    fn parse_whitespace() {
        let path = Path::new("file.rs").to_owned();
        let contents = r"
      [  ?tag   :  label            ]
      [  ?ref   :  label            ]
      [  ?file  :  foo/bar/baz.txt  ]
      [  ?dir   :  foo/bar/baz      ]
    "
        .trim()
        .replace('?', "")
        .as_bytes()
        .to_owned();
```

to something like:

```rust
    #[test]
    fn parse_whitespace() {
        let path = Path::new("file.rs").to_owned();
        let contents = r"
      [  ?tag   :  foo  bar             ]
      [  ?ref   :  foo  bar             ]
      [  ?file  :  foo bar/baz qux.txt  ]
      [  ?dir   :  foo bar/baz qux      ]
    "
        .trim()
        .replace('?', "")
        .as_bytes()
        .to_owned();
```

and update the assertions to make it pass.

2024-03-14 06:17 UTC, stepchowfun commented
I prefer to explicitly decree that the name of a tag cannot contain `]`. It's makes it easier to reason about in my opinion, because otherwise you have to think about lazy vs. greedy matching to know that `[tag:foo]bar]` has a tag called `foo` and not `foo]bar`.

The current regex allows for a tag with an empty name. I don't know of a good use case for that, but it doesn't seem problematic to me. I prefer to preserve the existing behavior if possible.

2024-03-14 07:18 UTC, vedang commented
Ack, I'll make the change accordingly

2024-03-14 07:32 UTC, vedang commented
Hi @stepchowfun

Please re-review the changes. I have made all the changes you asked for. 

On top of that, I also created a `const IDENTIFIER_REGEX_FMT_STR` in `[file:directive.rs]` to ensure that all the uses of the regex can be changed the next time we have to update it. 

The reason I did this is that in the initial commit that I pushed, all the tests were passing, but they were running against the old regex because it never occurred to me that the tests would use their own copy of the regular expression.

2024-03-14 07:45 UTC, stepchowfun commented
Thanks for updating the PR—I'll review it as soon as I can. In the meantime, would you mind rebasing onto the latest commit on `main`?

2024-03-14 07:55 UTC, vedang commented
Done @stepchowfun , it's rebased onto the latest `main`

2024-03-14 08:00 UTC, stepchowfun requested changes
Looking good—thanks for responding to my feedback. I've added a few minor comments.

2024-03-14 08:28 UTC, vedang commented
Ack, I'll make the changes

2024-03-14 08:48 UTC, vedang commented
Done, @stepchowfun . Please re-review the changes

2024-03-14 08:54 UTC, stepchowfun approved these changes
Looks good. I will merge it assuming the CI passes.

2024-03-14 09:17 UTC, merged